export const APP_SET_PATH = "APP_SET_PATH";

export const LOGIN_INPUT_CHANGED_HANDLER = "LOGIN_INPUT_CHANGED_HANDLER";
export const LOGIN_SUBMIT = "LOGIN_SUBMIT";

export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const SET_AUTH_REDIRECT_PATH = "SET_AUTH_REDIRECT_PATH";

//export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_START = "FORGOT_START";
export const FORGOT_FAIL = "FORGOT_FAIL";
export const FORGOT_SUCCESS = "FORGOT_SUCCESS";
export const INITIALIZE_STATE = "INITIALIZE_STATE";


export const USERS_REQUEST_START = "USERS_REQUEST_START";
export const USERS_REQUEST_FAIL = "USERS_REQUEST_FAIL";
export const USERS_REQUEST_SUCCESS = "USERS_REQUEST_SUCCESS";
export const USERS_DETAIL_SUCCESS = "USERS_DETAIL_SUCCESS";
export const LEVEL_UPDATE_SUCCESS ="LEVEL_UPDATE_SUCCESS";
export const USER_GROUP_UPDATE_SUCCESS ="USER_GROUP_UPDATE_SUCCESS";
export const GROUPS_REQUEST_SUCCESS ="GROUPS_REQUEST_SUCCESS";



export const DASHBOARD_SUCCESS = "DASHBOARD_SUCCESS";

export const OPEN_CHALLENGES_REQUEST_START = "OPEN_CHALLENGES_REQUEST_START";
export const OPEN_CHALLENGES_REQUEST_FAIL = "OPEN_CHALLENGES_REQUEST_FAIL";
export const OPEN_CHALLENGES_REQUEST_SUCCESS = "OPEN_CHALLENGES_REQUEST_SUCCESS";

export const MATCH_PLAYED_REQUEST_START = "MATCH_PLAYED_REQUEST_START";
export const MATCH_PLAYED_REQUEST_FAIL = "MATCH_PLAYED_REQUEST_FAIL";
export const MATCH_PLAYED_REQUEST_SUCCESS = "MATCH_PLAYED_REQUEST_SUCCESS";

export const OPEN_CONTENT_REQUEST_START = "OPEN_CONTENT_REQUEST_START";
export const OPEN_CONTENT_REQUEST_FAIL = "OPEN_CONTENT_REQUEST_FAIL";
export const OPEN_CONTENT_REQUEST_SUCCESS = "OPEN_CONTENT_REQUEST_SUCCESS";
export const GET_CONTENT_BY_SLUG = "GET_CONTENT_BY_SLUG";
export const UPDATE_CONTENT_REQUEST = "UPDATE_CONTENT_REQUEST";
export const UPDATE_CONTENT_SUCCESS = "UPDATE_CONTENT_SUCCESS";


export const NOTIFICATION_REQUEST_START = "NOTIFICATION_REQUEST_START";
export const NOTIFICATION_REQUEST_SUCCESS = "NOTIFICATION_REQUEST_SUCCESS";
export const NOTIFICATION_REQUEST_FAIL = "NOTIFICATION_REQUEST_FAIL";
export const NOTIFICATION_GRID_SUCCESS = "NOTIFICATION_GRID_SUCCESS";
export const NOTIFICATION_INITIALIZE_STATE = "NOTIFICATION_INITIALIZE_STATE";


export const ACCEPTED_CHALLENGES_REQUEST_SUCCESS = "ACCEPTED_CHALLENGES_REQUEST_SUCCESS";

export const GROUP_REQUEST_START = "GROUP_REQUEST_START";
export const GROUP_REQUEST_SUCCESS = "GROUP_REQUEST_SUCCESS";
export const GROUP_BY_ID = "GROUP_BY_ID";
export const GROUP_REQUEST_FAIL = "GROUP_REQUEST_FAIL";
export const GROUP_UPDATE_SUCCESS = "GROUP_UPDATE_SUCCESS";
export const GROUP_ADD_SUCCESS = "GROUP_ADD_SUCCESS";
export const GROUP_RESPONSE_FAIL = "GROUP_RESPONSE_FAIL";
export const SET_LOCATION_FLAG = "SET_LOCATION_FLAG";
export const DIVISION_BY_GROUP = "DIVISION_BY_GROUP";


export const FEEDBACK_REQUEST_START = "FEEDBACK_REQUEST_START";
export const FEEDBACK_REQUEST_SUCCESS = "FEEDBACK_REQUEST_SUCCESS";
export const FEEDBACK_BY_ID = "FEEDBACK_BY_ID";
export const FEEDBACK_REQUEST_FAIL = "FEEDBACK_REQUEST_FAIL";
export const FEEDBACK_RESPONSE_FAIL = "FEEDBACK_RESPONSE_FAIL";
export const FEEDBACK_REPLY_SUCCESS = "FEEDBACK_REPLY_SUCCESS";
export const FEEDBACK_INITIALIZE_STATE = "FEEDBACK_INITIALIZE_STATE";


export const RESET_PASSWORD_REQUEST_START = "RESET_PASSWORD_REQUEST_START";
export const RESET_PASSWORD_RESPONSE_FAIL = "RESET_PASSWORD_RESPONSE_FAIL";
export const RESET_PASSWORD_SUCCESS = "RESET_PASSWORD_SUCCESS";


export const PROFILE_REQUEST_START = "PROFILE_REQUEST_START";
export const PROFILE_REQUEST_SUCCESS = "PROFILE_REQUEST_SUCCESS";
export const PROFILE_BY_ID = "PROFILE_BY_ID";
export const PROFILE_REQUEST_FAIL = "PROFILE_REQUEST_FAIL";
export const PROFILE_UPDATE_SUCCESS = "PROFILE_UPDATE_SUCCESS";
export const PROFILE_RESPONSE_FAIL = "PROFILE_RESPONSE_FAIL";












